# Generated by Django 4.0.6 on 2023-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_tag_category_tags'),
        ('blog', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='builder.tag', verbose_name='Теги'),
        ),
    ]
