# Generated by Django 4.0.6 on 2023-01-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_body_de_article_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_de',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_de',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_de',
        ),
    ]
