# Generated by Django 4.0.6 on 2023-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_body_de_remove_article_description_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
    ]
