# Generated by Django 4.0.6 on 2023-02-03 12:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_article_body_ur_remove_article_description_ur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_be',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_uk',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_be',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_be',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_uk',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_be',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_uk',
        ),
        migrations.AddField(
            model_name='article',
            name='body_da',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_dsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_da',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_dsb',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='intro_da',
            field=models.TextField(null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='intro_dsb',
            field=models.TextField(null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_da',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_dsb',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
    ]
