# Generated by Django 4.0.6 on 2023-02-03 12:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_article_body_be_remove_article_body_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_da',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_dsb',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_da',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_dsb',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_da',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_dsb',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_da',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_dsb',
        ),
        migrations.AddField(
            model_name='article',
            name='body_af',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_af',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='intro_af',
            field=models.TextField(null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='intro_ar',
            field=models.TextField(null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_af',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
    ]
