# Generated by Django 4.0.6 on 2023-02-03 12:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_article_body_uk_remove_article_description_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_af',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_ar_dz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_af',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_ar_dz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_af',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_ar_dz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_af',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ar_dz',
        ),
        migrations.AddField(
            model_name='article',
            name='body_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_it',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='intro_it',
            field=models.TextField(null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='intro_uk',
            field=models.TextField(null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_it',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Назва'),
        ),
    ]
