# Generated by Django 4.0.6 on 2023-02-08 12:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0030_remove_category_description_af_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_remove_article_body_af_remove_article_body_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_it',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_it',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_it',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_en',
            field=models.TextField(null=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_uk',
            field=models.TextField(null=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date publish'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('standard', 'Standard'), ('top', 'Top'), ('banner', 'Banner')], default='standard', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='builder.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.template', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
