# Generated by Django 4.0.6 on 2023-02-11 08:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='intro_ru',
            field=models.TextField(null=True, verbose_name='Intro'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
    ]
