# Generated by Django 4.0.6 on 2023-02-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_article_body_af_remove_article_body_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='intro_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
    ]
