# Generated by Django 4.0.3 on 2022-06-27 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код знижки')),
                ('valid_from', models.DateTimeField(verbose_name='Дата активації')),
                ('valid_to', models.DateTimeField(verbose_name='Дата закінчення знижки')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка')),
                ('active', models.BooleanField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Знижка',
                'verbose_name_plural': 'Знижки',
                'ordering': ('-valid_from',),
            },
        ),
    ]
