# Generated by Django 4.0.3 on 2022-07-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product', verbose_name='Лінк на товар'),
        ),
        migrations.AddField(
            model_name='link',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.template', verbose_name='Шаблон блога'),
        ),
        migrations.AddField(
            model_name='image',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.template', verbose_name='Шаблон блога'),
        ),
        migrations.AddField(
            model_name='html',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.template', verbose_name='Шаблон блога'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='builder.category', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.template', verbose_name='Шаблон'),
        ),
    ]
