# Generated by Django 4.0.6 on 2022-09-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='builder.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('blog', 'Блог'), ('shop', 'Магазин')], default='blog', max_length=10, verbose_name='Тип категории'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('page', 'Сторінка'), ('blog', 'Категория блога'), ('shop', 'Категория магазину'), ('article', 'Стаття'), ('product', 'Товар'), ('link', 'Ссылка')], default='page', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('account', 'account'), ('admin', 'admin'), ('blog_1.html', 'blog_1.html'), ('default', 'default'), ('_header.html', '_header.html')], max_length=250, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('page', 'Сторінка'), ('blog', 'Блог'), ('article', 'Стаття'), ('shop', 'Магазин'), ('product', 'Товар'), ('block', 'Блок'), ('default', 'Универсальный')], max_length=10, verbose_name='Тип шаблона'),
        ),
    ]
