# Generated by Django 4.0.6 on 2022-11-04 13:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_category_parent_alter_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='html_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='html',
            name='html_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('blog_1.html', 'blog_1.html'), ('default_16.html', 'default_16.html'), ('_footer.html', '_footer.html'), ('_header.html', '_header.html'), ('admin', 'admin'), ('default', 'default'), ('default_login.html', 'default_login.html'), ('default_password_change.html', 'default_password_change.html'), ('default_profile.html', 'default_profile.html'), ('default_profile_edit.html', 'default_profile_edit.html'), ('default_register.html', 'default_register.html'), ('default_share.html', 'default_share.html'), ('default_404.html', 'default_404.html')], max_length=250, verbose_name='Шаблон'),
        ),
    ]
