# Generated by Django 4.0.6 on 2022-12-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_html_html_en_html_html_uk_alter_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('blog_1.html', 'blog_1.html'), ('default_16.html', 'default_16.html'), ('_footer.html', '_footer.html'), ('_header.html', '_header.html'), ('admin', 'admin'), ('default', 'default'), ('default_login.html', 'default_login.html'), ('default_password_change.html', 'default_password_change.html'), ('default_profile.html', 'default_profile.html'), ('default_profile_edit.html', 'default_profile_edit.html'), ('default_register.html', 'default_register.html'), ('default_share.html', 'default_share.html'), ('default_404.html', 'default_404.html'), ('blog_17.html', 'blog_17.html'), ('header.html', 'header.html'), ('breadcrumb.html', 'breadcrumb.html'), ('footer.html', 'footer.html'), ('blog_18.html', 'blog_18.html'), ('blog_22.html', 'blog_22.html'), ('blog_26.html', 'blog_26.html'), ('blog_30.html', 'blog_30.html'), ('blog_34.html', 'blog_34.html'), ('blog_38.html', 'blog_38.html'), ('blog_42.html', 'blog_42.html'), ('blog_46.html', 'blog_46.html'), ('blog_50.html', 'blog_50.html'), ('blog_54.html', 'blog_54.html'), ('blog_58.html', 'blog_58.html'), ('blog_62.html', 'blog_62.html'), ('blog_66.html', 'blog_66.html')], max_length=250, verbose_name='Шаблон'),
        ),
    ]
