# Generated by Django 4.0.6 on 2022-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_menu_icon_alter_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default_16.html', 'default_16.html'), ('_footer.html', '_footer.html'), ('_header.html', '_header.html'), ('admin', 'admin'), ('default', 'default'), ('default_login.html', 'default_login.html'), ('default_password_change.html', 'default_password_change.html'), ('default_profile.html', 'default_profile.html'), ('default_profile_edit.html', 'default_profile_edit.html'), ('default_register.html', 'default_register.html'), ('default_share.html', 'default_share.html'), ('default_404.html', 'default_404.html'), ('header.html', 'header.html'), ('breadcrumb.html', 'breadcrumb.html'), ('footer.html', 'footer.html'), ('blog_74.html', 'blog_74.html'), ('blog_78.html', 'blog_78.html'), ('blog_82.html', 'blog_82.html'), ('blog_86.html', 'blog_86.html'), ('blog_90.html', 'blog_90.html'), ('blog_93.html', 'blog_93.html'), ('blog_96.html', 'blog_96.html'), ('blog_99.html', 'blog_99.html')], max_length=250, verbose_name='Шаблон'),
        ),
    ]
