# Generated by Django 4.0.6 on 2022-12-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_alter_html_html_alter_html_html_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('admin', 'admin'), ('default', 'default'), ('default_login.html', 'default_login.html'), ('default_password_change.html', 'default_password_change.html'), ('default_profile.html', 'default_profile.html'), ('default_profile_edit.html', 'default_profile_edit.html'), ('default_register.html', 'default_register.html'), ('default_share.html', 'default_share.html'), ('default_404.html', 'default_404.html'), ('default_152.html', 'default_152.html'), ('header.html', 'header.html'), ('footer.html', 'footer.html'), ('blog_163.html', 'blog_163.html'), ('blog_164.html', 'blog_164.html'), ('blog_165.html', 'blog_165.html'), ('blog_166.html', 'blog_166.html'), ('404_167.html', '404_167.html')], max_length=250, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('page', 'Сторінка'), ('blog', 'Блог'), ('article', 'Стаття'), ('shop', 'Магазин'), ('product', 'Товар'), ('block', 'Блок'), ('default', 'Универсальный'), ('404', 'Error 404')], max_length=10, verbose_name='Тип шаблона'),
        ),
    ]
