# Generated by Django 4.0.6 on 2023-01-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_alter_link_title_alter_page_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='builder.template', verbose_name='Лінк на шаблон'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('page', 'Сторінка'), ('blog', 'Категория блога'), ('shop', 'Категория магазину'), ('article', 'Стаття'), ('product', 'Товар'), ('link', 'Ссылка'), ('template', 'Шаблон')], default='page', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('admin', 'admin'), ('default', 'default'), ('404_183.html', '404_183.html'), ('header.html', 'header.html'), ('sidebar.html', 'sidebar.html'), ('footer.html', 'footer.html'), ('blog_184.html', 'blog_184.html'), ('default_192.html', 'default_192.html'), ('default_login.html', 'default_login.html'), ('default_password_change.html', 'default_password_change.html'), ('default_profile.html', 'default_profile.html'), ('default_profile_edit.html', 'default_profile_edit.html'), ('default_register.html', 'default_register.html'), ('default_share.html', 'default_share.html'), ('default_404.html', 'default_404.html'), ('blog_196.html', 'blog_196.html'), ('blog_197.html', 'blog_197.html'), ('blog_199.html', 'blog_199.html'), ('article_202.html', 'article_202.html'), ('page_203.html', 'page_203.html')], max_length=250, verbose_name='Шаблон'),
        ),
    ]
