# Generated by Django 4.0.6 on 2023-01-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_menu_template_alter_menu_type_alter_page_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='page',
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('blog', 'Категория блога'), ('shop', 'Категория магазину'), ('article', 'Стаття'), ('product', 'Товар'), ('template', 'Шаблон'), ('link', 'Ссылка')], default='page', max_length=10, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
