# Generated by Django 4.0.6 on 2023-01-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('category', 'category'), ('article', 'article'), ('product', 'product'), ('template', 'template'), ('link', 'link')], default='page', max_length=10, verbose_name='Статус'),
        ),
    ]
