# Generated by Django 4.0.6 on 2023-01-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_alter_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
