# Generated by Django 4.0.6 on 2023-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_alter_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Посилання на головну сторінку'),
        ),
    ]
