# Generated by Django 4.0.6 on 2023-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_menu_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Посилання на головну сторінку'),
        ),
    ]
