# Generated by Django 4.0.6 on 2023-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_alter_menu_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Название')),
                ('title_uk', models.CharField(max_length=250, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обнавлено')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='builder.tag', verbose_name='Теги'),
        ),
    ]
