# Generated by Django 4.0.6 on 2023-01-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_tag_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lorem',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кількість беззмістовного матеріалу'),
        ),
    ]
