# Generated by Django 4.0.6 on 2023-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_category_lorem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
