# Generated by Django 4.0.6 on 2023-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0021_remove_category_description_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Код країни')),
                ('name', models.SlugField(max_length=250, unique=True, verbose_name='Країна')),
                ('status', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['id'],
            },
        ),
    ]
