# Generated by Django 4.0.6 on 2023-02-03 08:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0024_remove_category_description_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ur',
        ),
        migrations.RemoveField(
            model_name='category',
            name='intro_ur',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ur',
        ),
        migrations.RemoveField(
            model_name='html',
            name='html_ur',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description_ur',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_ur',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title_ur',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_ur',
        ),
        migrations.AddField(
            model_name='category',
            name='description_be',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro_be',
            field=models.TextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_be',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='html',
            name='html_be',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='menu',
            name='description_be',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_be',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_be',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='text',
            name='text_be',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
    ]
