# Generated by Django 4.0.6 on 2023-02-11 08:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0032_category_description_ru_category_intro_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='intro_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='intro_uk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='html',
            name='html_ru',
        ),
        migrations.RemoveField(
            model_name='html',
            name='html_uk',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_uk',
        ),
        migrations.AddField(
            model_name='category',
            name='description_af',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro_af',
            field=models.TextField(blank=True, null=True, verbose_name='Intro'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Intro'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_af',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='html',
            name='html_af',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Html'),
        ),
        migrations.AddField(
            model_name='html',
            name='html_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Html'),
        ),
        migrations.AddField(
            model_name='menu',
            name='description_af',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='menu',
            name='description_ar',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_af',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_af',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='text',
            name='text_af',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='text',
            name='text_ar',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Text'),
        ),
    ]
