# Generated by Django 4.0.6 on 2023-02-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0034_remove_category_description_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='intro_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='html',
            name='html_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_ru',
        ),
    ]
