# Generated by Django 4.0.6 on 2023-02-08 12:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0031_alter_category_options_alter_image_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['parent'], 'verbose_name': 'Filter', 'verbose_name_plural': 'Filters'},
        ),
        migrations.AlterModelOptions(
            name='filtername',
            options={'ordering': ['title'], 'verbose_name': 'Filter name', 'verbose_name_plural': 'Filter name'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='filter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.filtername', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='filtername',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='filtername',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='filtername',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='builder.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=250, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=250, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter',
            field=models.ManyToManyField(blank=True, to='shop.filter', verbose_name='Filter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img5',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_name_1',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Param name №1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_name_2',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Param name №2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_name_3',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Param name №3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_name_4',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Param name №4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_name_5',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Param name №5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_text_1',
            field=models.TextField(blank=True, null=True, verbose_name='Param text №1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Param text №2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_text_3',
            field=models.TextField(blank=True, null=True, verbose_name='Param text №3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_text_4',
            field=models.TextField(blank=True, null=True, verbose_name='Param text №4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='param_text_5',
            field=models.TextField(blank=True, null=True, verbose_name='Param text №5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('standard', 'standard'), ('top', 'Top')], default='standard', max_length=250, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text5',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video1',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video2',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video3',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video4',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video5',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='term',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='term',
            name='delivery',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='term',
            name='payment',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='term',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
